### ISSUE TITLE
Build wheels for arm/v7 in CI:

### ISSUE THREAD

**Issue by vojkovic** [searxng/fasttext-predict#8]
From the SearXNG matrix:

```
  |searxng|   Downloading fasttext-predict-0.9.2.2.tar.gz (16 kB)
  |searxng|   Preparing metadata (pyproject.toml): started
  |searxng|   Preparing metadata (pyproject.toml): finished with status 'error'
  |searxng|   error: subprocess-exited-with-error
  |searxng|   
  |searxng|   × Preparing metadata (pyproject.toml) did not run successfully.
  |searxng|   │ exit code: 1
  |searxng|   ╰─> [13 lines of output]
  |searxng|       Traceback (most recent call last):
  |searxng|         File "/usr/local/searxng/searx-pyenv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
  |searxng|           main()
  |searxng|         File "/usr/local/searxng/searx-pyenv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
  |searxng|           json_out['return_val'] = hook(**hook_input['kwargs'])
  |searxng|         File "/usr/local/searxng/searx-pyenv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
  |searxng|           return hook(metadata_directory, config_settings)
  |searxng|         File "/usr/local/searxng/searx-pyenv/lib/python3.9/site-packages/setuptools/build_meta.py", line 373, in prepare_metadata_for_build_wheel
  |searxng|           self.run_setup()
  |searxng|         File "/usr/local/searxng/searx-pyenv/lib/python3.9/site-packages/setuptools/build_meta.py", line 318, in run_setup
  |searxng|           exec(code, locals())
  |searxng|         File "<string>", line 15, in <module>
  |searxng|       ModuleNotFoundError: No module named 'pybind11'
  |searxng|       [end of output]
  |searxng|   
  |searxng|   note: This error originates from a subprocess, and is likely not a problem with pip.
  |searxng| error: metadata-generation-failed
  |searxng| 
  |searxng| × Encountered error while generating package metadata.
  |searxng| ╰─> See above for output.
  |searxng| 
  |searxng| note: This is an issue with the package mentioned above, not pip.
  |searxng| hint: See above for details.

```

Please update https://github.com/searxng/fasttext-predict/blob/main/.github/workflows/wheels.yml to build for armv7.

**Comment by dalf** [comment]
can you try the last version : v0.9.2.3

**Comment by dalf** [comment]
ahhh I just realize that `*-linux_armv7l.whl` are built but not uploaded.

See the end of https://github.com/searxng/fasttext-predict/actions/runs/11981151910/job/33407849727

```
 ===[ show_wheels ]===
+ ls -l /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp310-cp310-linux_armv7l.whl /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp310-cp310-musllinux_1_2_armv7l.whl /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp311-cp311-linux_armv7l.whl /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp311-cp311-musllinux_1_2_armv7l.whl /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp312-cp312-linux_armv7l.whl /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp312-cp312-musllinux_1_2_armv7l.whl /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp313-cp313-linux_armv7l.whl /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp313-cp313-musllinux_1_2_armv7l.whl /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp313-cp313t-linux_armv7l.whl /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp313-cp313t-musllinux_1_2_armv7l.whl /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp37-cp37m-linux_armv7l.whl /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp37-cp37m-musllinux_1_2_armv7l.whl /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp38-cp38-linux_armv7l.whl /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp38-cp38-musllinux_1_2_armv7l.whl /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp39-cp39-linux_armv7l.whl /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp39-cp39-musllinux_1_2_armv7l.whl
-rw-r--r--    1 root     root        272852 Nov 22 22:36 /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp310-cp310-linux_armv7l.whl
-rw-r--r--    1 root     root        913158 Nov 22 22:50 /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp310-cp310-musllinux_1_2_armv7l.whl
-rw-r--r--    1 root     root        276213 Nov 22 22:38 /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp311-cp311-linux_armv7l.whl
-rw-r--r--    1 root     root        913569 Nov 22 22:50 /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp311-cp311-musllinux_1_2_armv7l.whl
-rw-r--r--    1 root     root        275052 Nov 22 22:40 /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp312-cp312-linux_armv7l.whl
-rw-r--r--    1 root     root        913068 Nov 22 22:50 /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp312-cp312-musllinux_1_2_armv7l.whl
-rw-r--r--    1 root     root        275026 Nov 22 22:42 /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp313-cp313-linux_armv7l.whl
-rw-r--r--    1 root     root        913041 Nov 22 22:50 /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp313-cp313-musllinux_1_2_armv7l.whl
-rw-r--r--    1 root     root        277956 Nov 22 22:44 /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp313-cp313t-linux_armv7l.whl
-rw-r--r--    1 root     root        914171 Nov 22 22:50 /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp313-cp313t-musllinux_1_2_armv7l.whl
-rw-r--r--    1 root     root        102270 Nov 22 22:46 /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp37-cp37m-linux_armv7l.whl
-rw-r--r--    1 root     root        914469 Nov 22 22:50 /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp37-cp37m-musllinux_1_2_armv7l.whl
-rw-r--r--    1 root     root        272773 Nov 22 22:48 /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp38-cp38-linux_armv7l.whl
-rw-r--r--    1 root     root        913003 Nov 22 22:50 /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp38-cp38-musllinux_1_2_armv7l.whl
-rw-r--r--    1 root     root        272968 Nov 22 22:50 /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp39-cp39-linux_armv7l.whl
-rw-r--r--    1 root     root        913515 Nov 22 22:51 /io/wheelhouse/musllinux_1_2_armv7l/fasttext_predict-0.9.2.3-cp39-cp39-musllinux_1_2_armv7l.whl
0.08user 0.08system 17:23.79elapsed 0%CPU (0avgtext+0avgdata 33372maxresident)k
0inputs+0outputs (1major+1787minor)pagefaults 0swaps
```

But because of
https://github.com/searxng/fasttext-predict/blob/f2da9cd17366c3fa99e7b8d7416de2ddeae55cc0/.github/workflows/wheels.yml#L114

`*-linux_armv7l.whl` are ignored.

**Comment by dalf** [comment]
So v0.9.2.3 is missing manylinux armv7l wheels (it includes the musllinux armv7l but most probably this is not what you are looking for).

I changed the [GitHub workflow on dalf/fasttext-predict](https://github.com/dalf/fasttext-predict/blob/main/.github/workflows/wheels.yml) to use [cibuildwheel](https://cibuildwheel.pypa.io/en/stable/).

See this release:
https://github.com/dalf/fasttext-predict/releases/tag/v0.0.0.1

If this works as expected, I will release a v0.9.2.4 version based on this GH workflow.
